// export function test(){fetch('apprenants.json')
// .then((response) => response.json())
// .then((data) => {
//     console.log(getApprenants(data))
// })
// .catch((error) => {
//     console.error('Une erreur est survenue lors de la recuperation du fichier JSON', error)
// })}